name: Deploy to Server

on:
  push:
    branches:
      - master # 触发的分支

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}     # 服务器IP
          username: ${{ secrets.SERVER_USER }} # 服务器用户名
          key: ${{ secrets.SERVER_SSH_KEY }}   # 服务器私钥
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            if [ ! -d "/var/www/moyuban" ]; then
              sudo mkdir -p /var/www/moyuban
              sudo chown -R $(whoami) /var/www/moyuban
              git clone https://github.com/alongLFB/moyuban.git /var/www/moyuban
            fi

            cd /var/www/moyuban
            git fetch origin master
            git reset --hard origin/master
            sudo chmod -R a+rX /var/www/moyuban
